import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const g=createRequire(import.meta.url)('../app.js');
const s=g.createInitialState('收成','li','standard');s.cash=200;
const forecast=g.enterpriseForecast(s,'old_street','commerce',1);
assert.equal(s.territories.old_street.industry,'','preview does not mutate the save');
g.developEnterprise(s,'old_street','commerce');
assert.equal(s.territories.old_street.invested,26);
assert.equal(g.enterpriseProfit(s,'old_street'),0);
g.enterpriseTick(s);const rep=s.rep;g.enterpriseTick(s);
assert.equal(s.rep,Math.min(100,rep+2));assert.equal(s.businessNews.length,1);
assert.ok(Math.abs(g.enterpriseProfit(s,'old_street')-forecast)<=1);
g.recordEnterpriseEarnings(s);assert.equal(s.territories.old_street.earned,g.enterpriseProfit(s,'old_street'));
for(let i=0;i<12;i++){g.enterpriseTick(s);g.recordEnterpriseEarnings(s)}
assert.ok(s.territories.old_street.paidBack);
g.enterpriseTick(s);g.recordEnterpriseEarnings(s);assert.equal(s.businessNews.length,0,'no repeat payback notification');
s.territories.clocktower.owner='player';const cash=s.cash;
assert.deepEqual(g.districtHonors(s),['油尖旺区']);assert.equal(s.cash,cash+8);
s.territories.clocktower.owner='free';g.districtHonors(s);s.territories.clocktower.owner='player';assert.deepEqual(g.districtHonors(s),[]);
const restored=g.normalizeState(JSON.parse(JSON.stringify(s)));assert.deepEqual(g.districtHonors(restored),[],'reload cannot farm district gifts');
assert.equal(restored.territories.old_street.earned,s.territories.old_street.earned);
console.log('Business forecasts, opening, earnings, payback and district rewards passed');
const battle=g.createInitialState('战果','yi','standard');battle.crew=1500;battle.territories.clocktower.guard=10;
const beforeCash=battle.cash;
const report=g.resolveBattle(battle,{targetId:'clocktower',leaderIds:['player','zhaokui','chengye'],troops:1000,tactic:'steady'},()=>.5);
assert.ok(report.won);assert.deepEqual(report.honors,['油尖旺区']);
assert.equal(report.cashGain,Math.round((battle.cash-beforeCash)*10)/10);
assert.equal(report.survivors+report.garrison+report.losses,report.troops,'整补＋留守＋折损＝出战');
assert.ok(report.garrison>0&&battle.territories.clocktower.guard===report.garrison,'留守的人就是新地盘的驻防');
assert.equal(g.finishBattle(battle),null,'settled battle cannot pay twice');
console.log('Victory report and one-time settlement passed');
